const WEATHER_CODES = { 0: ["Clear sky", "☀️"], 1: ["Mostly clear", "🌤️"], 2: ["Partly cloudy", "⛅"], 3: ["Overcast", "☁️"], 45: ["Foggy", "🌫️"], 48: ["Foggy", "🌫️"], 51: ["Light drizzle", "🌦️"], 53: ["Drizzle", "🌦️"], 55: ["Heavy drizzle", "🌧️"], 61: ["Light rain", "🌦️"], 63: ["Rain", "🌧️"], 65: ["Heavy rain", "🌧️"], 71: ["Light snow", "🌨️"], 73: ["Snow", "❄️"], 75: ["Heavy snow", "❄️"], 80: ["Rain showers", "🌦️"], 81: ["Rain showers", "🌧️"], 82: ["Violent rain showers", "⛈️"], 85: ["Snow showers", "🌨️"], 86: ["Snow showers", "🌨️"], 95: ["Thunderstorm", "⛈️"], 96: ["Thunderstorm with hail", "⛈️"], 99: ["Thunderstorm with hail", "⛈️"] };
const elements = Object.fromEntries(["score", "mode-label", "status-dot", "status-message", "place-card", "place-photo", "place-region", "place-name", "place-time", "weather-condition", "weather-temp", "time-fact", "condition-fact", "temperature-fact", "randomize-btn", "guess-panel", "guess-prompt", "guess-form", "guess-input", "history-panel", "history-count", "guess-history"].map((id) => [id.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()), document.getElementById(id)]));
const modeButtons = document.querySelectorAll(".mode-card");
let mode = "weather";
let current = null;
let score = 0;
let cooldownUntil = 0;
let cooldownTimer = null;
let clockTimer = null;
const history = [];

function regionText(city) { return city.region ? `${city.region}, ${city.country}` : city.country; }
function modeName() { return mode === "weather" ? "WEATHER ROUND" : mode === "time" ? "TIME ROUND" : "EXPLORE"; }
function setStatus(message, ready = false) { elements.statusMessage.textContent = message; elements.statusDot.classList.toggle("ready", ready); }
function setMode(nextMode) { mode = nextMode; modeButtons.forEach((button) => { const active = button.dataset.mode === mode; button.classList.toggle("active", active); button.setAttribute("aria-pressed", String(active)); }); elements.modeLabel.textContent = modeName(); elements.timeFact.classList.toggle("hidden", mode === "time"); elements.conditionFact.classList.toggle("hidden", mode === "weather"); elements.temperatureFact.classList.toggle("hidden", mode === "weather"); elements.guessPanel.classList.toggle("hidden", mode === "explore" || !current); elements.guessPrompt.textContent = mode === "weather" ? "Type the weather condition" : "Type the local time"; elements.guessInput.placeholder = mode === "weather" ? "sunny, rain, partly cloudy..." : "e.g. 8:42 PM"; if (mode === "explore") setStatus("No score, no clock, no pressure. Spin freely.", true); else if (current) setStatus(mode === "weather" ? "What are the conditions in this city?" : "What time is it in this city?", true); }
function pickCity() { return WORLD_ROULETTE_CITIES[Math.floor(Math.random() * WORLD_ROULETTE_CITIES.length)]; }
async function getWeather(city) { try { const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${city.lat}&longitude=${city.lon}&current=temperature_2m,weather_code&temperature_unit=fahrenheit&timezone=auto`); if (!response.ok) throw new Error("Weather unavailable"); const data = await response.json(); if (!data.current) throw new Error("Weather data unavailable"); return { timezone: data.timezone, current: data.current, live: true }; } catch (error) { return { timezone: "UTC", current: { temperature_2m: 20, weather_code: 0 }, live: false }; } }
async function getPhoto(city) { for (const query of [city.name, `${city.name}, ${city.country}`]) { try { const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(query)}`); if (response.ok) { const data = await response.json(); if (data.thumbnail?.source) return data.thumbnail.source; } } catch (error) { /* Continue to the next image query. */ } } return "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80"; }
function updateClock(timezone) { const text = new Date().toLocaleTimeString("en-US", { timeZone: timezone, hour: "numeric", minute: "2-digit" }); elements.placeTime.textContent = text; current.timeText = text; }
function startClock(timezone) { clearInterval(clockTimer); updateClock(timezone); clockTimer = setInterval(() => updateClock(timezone), 15000); }
async function spin() { if (Date.now() < cooldownUntil) return; elements.randomizeBtn.disabled = true; elements.guessPanel.classList.add("hidden"); elements.placeCard.classList.add("hidden"); setStatus("Finding your next city..."); try { const city = pickCity(); const weather = await getWeather(city); const photo = await getPhoto(city).catch(() => ""); const info = WEATHER_CODES[weather.current.weather_code] || ["Unknown", "🌡️"]; current = { city, timezone: weather.timezone, condition: info[0], emoji: info[1], temperature: Math.round(weather.current.temperature_2m), timeText: "" }; elements.placePhoto.src = photo; elements.placePhoto.alt = `A view of ${city.name}`; document.querySelector(".city-backdrop").style.backgroundImage = `url("${photo}")`; document.querySelector(".city-backdrop").classList.add("visible"); elements.placeRegion.textContent = regionText(city); elements.placeName.textContent = city.name; elements.weatherCondition.textContent = `${info[1]} ${info[0]}`; elements.weatherTemp.textContent = `${current.temperature}°F`; startClock(weather.timezone); elements.placeCard.classList.remove("hidden"); if (mode !== "explore") { elements.guessPanel.classList.remove("hidden"); setStatus(weather.live ? (mode === "weather" ? "What are the conditions in this city?" : "What time is it in this city?") : "Preview data is showing while live weather reconnects.", true); } else { setStatus(weather.live ? "Explore mode: spin again whenever you like." : "Preview data is showing while live weather reconnects.", true); } elements.randomizeBtn.disabled = false; } catch (error) { setStatus("That spin missed the signal. Try again."); elements.randomizeBtn.disabled = false; } }
function addHistory(result, detail) { history.unshift({ city: current.city.name, result, detail }); elements.historyPanel.classList.remove("hidden"); elements.historyCount.textContent = `${history.length} round${history.length === 1 ? "" : "s"}`; elements.guessHistory.innerHTML = history.map((item) => `<div class="history-item"><strong>${item.city}</strong><span>${item.detail}</span><span class="result ${item.result === "miss" ? "miss" : ""}">${item.result === "hit" ? "Correct" : "Missed"}</span></div>`).join(""); }
function minutesFromInput(value) { const match = value.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/i); if (!match) return null; let hour = Number(match[1]); const minute = Number(match[2] || 0); const meridiem = match[3]?.toLowerCase(); if (minute > 59) return null; if (meridiem) { if (hour < 1 || hour > 12) return null; if (hour === 12) hour = 0; if (meridiem === "pm") hour += 12; } else if (hour > 23) return null; return hour * 60 + minute; }
function weatherAnswerMatches(value, condition) { const guess = value.toLowerCase().replace(/[^a-z ]/g, "").trim(); const answer = condition.toLowerCase(); const aliases = { "clear sky": ["clear", "sunny", "clear sky"], "mostly clear": ["clear", "sunny", "mostly clear"], "partly cloudy": ["partly cloudy", "partly cloudly", "partly cloudy skies"], "overcast": ["overcast", "cloudy", "clouds"], "light rain": ["rain", "light rain", "rainy"], "rain": ["rain", "rainy"], "heavy rain": ["rain", "heavy rain", "rainy"], "rain showers": ["rain", "showers", "rain showers"], "foggy": ["fog", "foggy"], "light snow": ["snow", "light snow", "snowy"], "snow": ["snow", "snowy"], "heavy snow": ["snow", "heavy snow", "snowy"], "thunderstorm": ["storm", "thunderstorm", "thunder"], "drizzle": ["drizzle", "rain"], "heavy drizzle": ["drizzle", "rain"] }; return (aliases[answer] || [answer]).includes(guess); }
function answer(value) { if (!current || mode === "explore") return; const cleanValue = value.trim(); const weatherCorrect = mode === "weather" && weatherAnswerMatches(cleanValue, current.condition); const guessedMinutes = mode === "time" ? minutesFromInput(cleanValue) : null; const actualMinutes = mode === "time" ? minutesFromInput(current.timeText) : null; const timeCorrect = guessedMinutes !== null && actualMinutes !== null && Math.min(Math.abs(guessedMinutes - actualMinutes), 1440 - Math.abs(guessedMinutes - actualMinutes)) <= 1; const wasCorrect = weatherCorrect || timeCorrect; const detail = mode === "weather" ? current.condition : current.timeText; addHistory(wasCorrect ? "hit" : "miss", `${cleanValue} · ${detail}`); elements.guessInput.value = ""; if (wasCorrect) { score += 1; elements.score.textContent = score; elements.guessPanel.classList.add("hidden"); if (score >= 3) { setStatus("You win. Three correct answers across the world.", true); elements.randomizeBtn.disabled = false; return; } setStatus(`Correct. ${score}/3 complete. Spin for the next city.`, true); elements.randomizeBtn.disabled = false; } else { cooldownUntil = Date.now() + 20000; elements.guessPanel.classList.add("hidden"); setStatus(mode === "weather" ? `The answer was ${current.condition}. New city in 20 seconds.` : `The local time was ${current.timeText}. New city in 20 seconds.`); clearInterval(cooldownTimer); const tick = () => { const seconds = Math.max(0, Math.ceil((cooldownUntil - Date.now()) / 1000)); if (!seconds) { elements.randomizeBtn.disabled = false; setStatus("Cooldown over. Spin for another city.", true); return; } elements.randomizeBtn.disabled = true; setStatus(`The answer was ${mode === "weather" ? current.condition : current.timeText}. New city in ${seconds}s.`); cooldownTimer = setTimeout(tick, 1000); }; tick(); } }
modeButtons.forEach((button) => button.addEventListener("click", () => setMode(button.dataset.mode)));
elements.randomizeBtn.addEventListener("click", spin);
elements.guessForm.addEventListener("submit", (event) => { event.preventDefault(); answer(elements.guessInput.value); });
setMode(mode);
spin();
