/* Guesspionage - percentage prompts. Each answer is the real-ish share, 0-100. */

const PROMPTS = [
  { text: "What percentage of people say Pikachu is their favourite Pok\u00e9mon?", answer: 21 },
  { text: "What percentage of people have played a Pok\u00e9mon game?", answer: 62 },
  { text: "What percentage of people can name all three Kanto starters?", answer: 74 },
  { text: "What percentage of people picked Charmander as their first starter?", answer: 41 },
  { text: "What percentage of people have caught a shiny Pok\u00e9mon?", answer: 18 },
  { text: "What percentage of people nickname their Pok\u00e9mon?", answer: 47 },
  { text: "What percentage of people say they'd own a Snorlax if they could?", answer: 55 },
  { text: "What percentage of people have watched at least one episode of the anime?", answer: 71 },
  { text: "What percentage of people can hum the Pok\u00e9mon theme song?", answer: 66 },
  { text: "What percentage of people think Jigglypuff is annoying?", answer: 38 },
  { text: "What percentage of people would rather have a fire type than a water type?", answer: 52 },
  { text: "What percentage of people have never finished a Pok\u00e9mon game?", answer: 34 },
  { text: "What percentage of people say Magikarp is useless?", answer: 58 },
  { text: "What percentage of people have traded a Pok\u00e9mon with a friend?", answer: 49 },
  { text: "What percentage of people would eat a Slowpoke Tail?", answer: 12 },
  { text: "What percentage of people believe Mew is under that truck?", answer: 27 },
  { text: "What percentage of people say Gengar is scarier than Mimikyu?", answer: 44 },
  { text: "What percentage of people played Pok\u00e9mon GO in 2016?", answer: 68 },
  { text: "What percentage of people still play Pok\u00e9mon GO today?", answer: 14 },
  { text: "What percentage of people can spell 'Pok\u00e9mon' with the accent?", answer: 31 },
  { text: "What percentage of people think Team Rocket are the real heroes?", answer: 23 },
  { text: "What percentage of people have cried at a Pok\u00e9mon episode?", answer: 36 },
  { text: "What percentage of people own at least one piece of Pok\u00e9mon merch?", answer: 57 },
  { text: "What percentage of people say Eevee is the cutest Pok\u00e9mon?", answer: 43 },
  { text: "What percentage of people would rather fly on a Charizard than drive a car?", answer: 79 },
  { text: "What percentage of people can name a single Pok\u00e9mon from Unova?", answer: 46 },
  { text: "What percentage of people think there are too many Pok\u00e9mon now?", answer: 53 },
  { text: "What percentage of people have used a Master Ball on a random encounter?", answer: 16 },
  { text: "What percentage of people say Snorlax is the best sleeper in fiction?", answer: 61 },
  { text: "What percentage of people would name their pet after a Pok\u00e9mon?", answer: 29 },
];
